name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: embassy

    steps:
    - uses: actions/checkout@v4
    - name: Install ARMv7 target
      run: rustup target add thumbv7m-none-eabi
    - name: Build
      run: cargo build --bin votol --release --verbose
    - name: Run tests
      run: cargo test --verbose
